repos:
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: remove-crlf
    -   id: forbid-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
-   repo: local
    hooks:
    -   id: python-unit-tests
        name: py.test
        language: system
        entry: sh -c py.test
        files: ''
